data_path: ../../data/recsys_data
dataset: lastfm_recbole

use_gpu: False
device: cpu
# save_dataset: True
# save_dataloaders: True

Vectorizer: TfIdfVectorizer
Vectorized_Col: tags
Vectorizer_Config:
  min_df: 1
  binary: True

weighted_average: False
knn_topk: ~

# Dataset config
load_col:
  inter: [user_id, track_id, rating, timestamp]
  item: [track_id, tags] # Include tags
  user: [user_id]

USER_ID_FIELD: user_id
ITEM_ID_FIELD: track_id
normalize_all: True

# Training and evaluation config
epochs: 1
train_batch_size: 4096
eval_batch_size: 4096

train_neg_sample_args: 
  distribution: uniform

eval_args:
  split: {'RS': [1.0,0.1,0.1]}
  order: RO
  group_by: user
  # mode: uni100
  mode: full

metrics: [Recall, MRR, NDCG, Hit, Precision]
topk: 20
valid_metric: NDCG@20
