data_path: ../../data/recsys_data
dataset: lastfm_recbole

USER_ID_FIELD: user_id
ITEM_ID_FIELD: track_id
RATING_FIELD: rating
TIME_FIELD: timestamp

load_col:
    inter: [user_id, track_id, rating, timestamp]

threshold: {'rating': 2}
normalize_all: True

# Training and evaluation config
eval_args:
    group_by: None
    mode: labeled
metrics: ['AUC', 'LogLoss', 'RMSE']
valid_metric: AUC

# metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
# topk: 20
# valid_metric: MRR@20

epochs: 500
train_batch_size: 4096
eval_batch_size: 4096
