data_path: ../../data/recsys_data
dataset_save_path: saved/lastfm_recbole-dataset.pth
dataset: lastfm_recbole

use_gpu: false
device: cpu

# Dataset config
load_col:
  inter: [user_id, track_id, rating, timestamp]
  item: [track_id, artist_id, tags, v, a, d, stsc] # ARTIST + TAG_SEQS + VADST
  # item: [track_id] # NO ADDITIONAL DATA
  user: [user_id]

numerical_features: [v, a, d, stsc]

USER_ID_FIELD: user_id
ITEM_ID_FIELD: track_id
normalize_all: True

# Training and evaluation config
epochs: 10
train_batch_size: 4096
eval_batch_size: 4096
stopping_step: 2

train_neg_sample_args: 
  distribution: uniform

eval_args:
  split: {'RS': [0.8,0.1,0.1]}
  order: RO
  group_by: user
  # mode: uni100
  mode: full

# metrics: ['AUC', 'LogLoss', 'RMSE', 'MAE']
# valid_metric: LogLoss

metrics: [Recall, MRR, NDCG, MAP, Precision]
topk: 20
valid_metric: NDCG@20
