data_path: ../../data/recsys_data
dataset_save_path: saved/lastfm_recbole-dataset.pth
dataset: lastfm_recbole

use_gpu: False
device: cpu

# V A D StSc
use_vadst_cols: [0,1,2,3]
weighted_average: False
knn_topk: ~

# Dataset config
load_col:
  inter: [user_id, track_id, rating, timestamp]
  item: [track_id, artist_id, album_id, tags, vadst] # ARTIST + ALBUM + TAG_SEQS + VADST
  user: [user_id]

USER_ID_FIELD: user_id
ITEM_ID_FIELD: track_id
normalize_all: True

# Training and evaluation config
epochs: 1
train_batch_size: 4096
eval_batch_size: 4096

train_neg_sample_args: 
  distribution: uniform

eval_args:
  split: {'RS': [0.8,0.1,0.1]}
  order: RO
  group_by: user
  # mode: uni100
  mode: full

metrics: [Recall, MRR, NDCG, Hit, Precision]
topk: 100
valid_metric: NDCG@100
